import 'semantic-ui-css/semantic.min.css';
import {React, Suspense} from "react";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
 return (
    <html lang="en">
      <body>
      <Suspense fallback={<p>wait till it loads</p>}>
          <div className='ui container' style={{paddingTop: "20px"}}>  
          {children}
          </div>
          </Suspense>
        </body>
    </html>
  )
}
